### PR TITLE
Deactivate Xdebug By Default - closes #99

### LINKED ISSUE #99: Xdebug deactivation in behat images does not work
`phpdismod` is overridden by the entrypoint script.

Best way is to add an environment variable to this script to activate Xdebug.

It should be deactivate by default.

Environment variable should all be present (even if commented) in the compose files provided in the repository.

### PR DESCRIPTION
**Pull request by anaelChardan**

### CODE REVIEW

**Review by damien-carcel — CHANGES_REQUESTED** [review]
In `COMPOSE.md`, there are install instructions that tell the user to deactivate Xdebug, install the PIM, then reactivate. These instructions should be dropped now.

Plus, in `php` image, please deactivate `xdebug`, on the same line we activate `mcrypt`

**Comment by anaelChardan** [comment]
Compose.md is already done too :)

**Comment by anaelChardan** [comment]
Corrected

**Comment by damien-carcel** [comment]
I was taking about this par in COMPOSE.md:

```bash
$ docker-compose exec akeneo sudo php5dismod -s cli xdebug
$ docker-compose exec akeneo php -d memory_limit=-1 /usr/local/bin/composer update
$ docker-compose exec akeneo pim-initialize
$ docker-compose exec akeneo sudo php5enmod -s cli xdebug
```

;-)

First and last lines are not needed anymore.

**Comment by anaelChardan** [comment]
Ah yes, sorry :) So corrected :-P

**Review by damien-carcel — APPROVED** [review]

**Pull request merged**
