### PR TITLE
Add PHP 7.3 support (closes #329)

### LINKED ISSUE #329: Add PHP 7.3
| Q                      | A
| ---------------------- | -----
| Bug report?            | no
| Feature request?       | yes
| BC Break report?       | no
| RFC?                   | no
| Affected image and tag | akeneo/php, akeneo/fpm

Create new tags `akeneo/php:7.3` and `akeneo/fpm:php-7.3`.

### PR DESCRIPTION
**Pull request by stefandoorn**
## Definition Of Done

| Q                                 | A
| --------------------------------- | ---
| Added tests                       | OK
| Changelog updated                 | OK
| Documentation                     | OK
| Fixed tickets                     | #329 

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Review by jmleroux — APPROVED** [review]

**Review by damien-carcel — APPROVED** [review]
Hello @stefandoorn.

Great Job, thank you so much for this contribution!.

I asked my teammates for another review (we require 2 approvals to merge a PR) then I will merge.
I'll let you know when the new images are generated on Docker Hub.

Cheers,
Damien

**Comment by damien-carcel** [comment]
`akeneo:php` and `akeneo:fpm` are available on Docker Hub for PHP 7.3 :tada:

**Comment by stefandoorn** [comment]
You're welcome @damien-carcel. What about the Apache/PHP setup for 7.2 & 7.3? Is that discontinued or just not implemented yet?

**Comment by damien-carcel** [comment]
`akeneo/apache-php` is indeed discontinued. We are only using FPM now.
The 7.0 and 7.1 versions were experimental, only the 5.6 version is used with Akeneo 1.7. And as it will reach end of support by the end of March, we will fully deprecate `akeneo/apache-php`, remove them from the GitHub repository and not build them anymore (current tags will stay on the Docker hub).

**Comment by stefandoorn** [comment]
@damien-carcel Actually I figured out today that Akeneo itself is not compatible with PHP 7.3 due to older Doctrine versions: https://github.com/akeneo/pim-community-dev/issues/9623. Although it's not the responsibility of the Docker set-up, it would maybe make sense to test an installation on the Docker files also? That's what they are intended for in the end.. :-)

**Comment by damien-carcel** [comment]
Indeed, they are.

We know Akeneo 3.x cannot support PHP 7.3 because of several dependencies (there were also a few issues with some of our dev dependencies when I checked before Christmas).

We couldn't work on it for Akeneo 3.x because of the tied schedule, but Akeneo 4.x (next year major release) will very probably require PHP 7.3, maybe PHP 7.4 if we have the time to test it and find no major issues.

Creating images for the new PHP versions is the first step for that (now done thanks to you :slightly_smiling_face:).

**Comment by stefandoorn** [comment]
That's a pity. It would be great if 3.x is going to support it (not necessarily require it), because active support for PHP 7.2 ends already in 9 months from now.

**Pull request merged**
