### PR TITLE
PIM-7903: remove mbstring extension for PHP 7.0 and 7.1

### PR DESCRIPTION
**Pull request by rouliane**
## Description

mbstring extension is not in the PIM requirements

## Definition Of Done

| Q                                 | A
| --------------------------------- | ---
| Added tests                       | -
| Changelog updated                 | Todo
| Documentation                     | -
| Fixed tickets                     | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Review by ahocquard — APPROVED** [review]

**Review by jmleroux — APPROVED** [review]
We could also check the Ansible roles

**Review by damien-carcel — CHANGES_REQUESTED** [review]
`mb_ereg_replace` is used in EE 2.0 and 2.3, so we cannot remove this extension from the images.
Maybe it was a mistake to use it (`mbstring` is used only once, in EE) and we should fix the PIM. Then we could remove the extension.

And please update changelog :slightly_smiling_face:.

**Comment by rouliane** [comment]
/!\ Do not merge until this PR is not merged AND the 2.0->2.3 pullup is done :
akeneo/pim-enterprise-dev#5160

**Review by damien-carcel — APPROVED** [review]
`mbstring` as been removed from the PIM 2.x. GTM.

**Pull request merged**
