### PR TITLE
Issue 284: Move all versions in master branch

### PR DESCRIPTION
**Pull request by damien-carcel**
## Description

This PR moves all the maintained images in the branch master, and use sub-folders for separating PHP versions. New Dockerfiles and there configuration files are just copy of the ones that were in separate branches, nothing more.

The Dockerfile of the latest version (currently PHP 7.1) is at the root of the image folder (for instance, `akeneo/php` is in `php/Dockerfile`) while previous versions are in subfolders (like `php/7.0/Dockerfile`).

This choice allows to have only one README.md file at the root of each image folder, which will be used to update Docker Hub main pages during automated builds.

### Note

This organization could changed in the future if the build of the images (and the update of the README) is fully done by the CI, not by Docker Hub anymore. Then the latest images could be in their own sub-folders like the previous versions.

## Definition Of Done

| Q                                 | A
| --------------------------------- | ---
| Added tests                       | OK
| Changelog updated                 | OK
| Documentation                     | OK
| Fixed tickets                     | #284

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by ClementGautier** [comment]
Why not put `php/Dockerfile` in `php/latest/Dockerfile` ? Would be clearer in my opinion. Otherwize good job ! this is much more simple for maintainance ;)

**Review by ClementGautier — CHANGES_REQUESTED** [review]
Why not put `php/Dockerfile` in `php/latest/Dockerfile` ? Would be clearer in my opinion. Otherwize good job ! I was waiting for that ;)

**Comment by damien-carcel** [comment]
It is only for the README file. I though this was the simplest solution. The real one would be to have a CI build, all images in their subfolders, and the README alone at root, like for official Docker library images.

**Comment by damien-carcel** [comment]
It could be in a 7.1 folder, with the README in it. One would only have to remember to move the README when adding a new version. But I don't like the README being hidden like that, that's why I choose this solution.

**Review by ClementGautier — APPROVED** [review]

**Pull request merged**
