### PR TITLE
PIM-MASTER: Add NPM as a dependency and update scripts

### PR DESCRIPTION
**Pull request by anaelChardan**

### CODE REVIEW

**Comment by damien-carcel** [comment]
Hello @anaelChardan.

Sorry but no :-). I though of this some times ago (https://github.com/damien-carcel/Dockerfiles/issues/66), and came again to the same conclusion with @nidup this week: this is not to be in PHP or Akeneo containers. There is official NodeJS/NPM image that should be used.

@nidup will maybe do a PR on the documentation, to add the usage of this image in the compose files. I just created an issue for this topic: https://github.com/damien-carcel/Dockerfiles/issues/224 (and another one for Elasticsearch: https://github.com/damien-carcel/Dockerfiles/issues/225, now that Single Storage is out).

**Comment by anaelChardan** [comment]
I understand for ES but I don't understand for the npm scripts as this is not a service but a package manager used at a certain time, but I'm sure you have a good answer to explain me the reason :).

**Comment by damien-carcel** [comment]
Yes I have, three of them to be precise :-).

- As I said previously, my images are PHP, and only PHP images (the Apache-PHP contains Apache only because mod_php is not installable without it, if it was, I would have a separate Apache image, like for nginx and FPM). So I just don't want anything related to NodeJS and JavaScript specific in it.

- This problem does not exists for the moment, but we can imagine that at one point, new versions of NodeJS and NPM will be needed for new versions of Akeneo, and this version evolution could not be synchronized with PHP, resulting with new labels for PHP images:
    - PHP 7.x with Node 8
    - PHP 7.y with node 8
    - PHP 7.y with node 9
    - …

  I don't want this situation. Separate images allow to have separate versioning much easier.

- When developing front on Akeneo next version, we will use `npm run webpack-watch` to recompile JS and LESS on the run and refresh the web browser.
  Now, imagine you are running that, then want to do some debug on PHP: you activate XDebug and restart the container, so you kill the webpack watcher, and need to restart it too.
  If you have NodeJS/NPM in a separate container, independent from the PHP one, then you can restart PHP container without killing the webpack watcher, and _vice versa_. 

And there is probably a lot of other situations I didn't think about. The only drawback of this is that we cannot just run `pim-initialize` anymore, but need a second command for the `webpack` part. However, this can be done with a local script on your host machine.

**Comment by anaelChardan** [comment]
Ok, thanks I understand now :).

**Pull request closed without merging**
