### PR TITLE
Add a command for `cache:clear` and dump assets as symlinks - closes #100

### LINKED ISSUE #100: Enhance provided commands
Like there is a command `pim-initialize` and `pim-in-ass`, there should be a command `pim-cac`:
- rm -rf app/cache/*
- app/console ca:c -e=prod
- app/console ca:c

Also, `pim-initialize` and `pim-in-ass` should dump assets as symlinks even in behat images.

### PR DESCRIPTION
**Pull request by anaelChardan**

### CODE REVIEW

**Comment by damien-carcel** [comment]
Thanks for the PR @anaelChardan.

The pim-cac command is also needed in behat (with `-e=behat` argument). Also, all these changes are also to be made on `akeneo-fpm` and `akeneo-behat-fpm` images.

**Review by damien-carcel — CHANGES_REQUESTED** [review]
Thanks for the PR @anaelChardan.

The pim-cac command is also needed in behat (with `-e=behat` argument). Also, all these changes are also to be made on `akeneo-fpm` and `akeneo-behat-fpm` images.

With that, it will be mergeable!

**Comment by anaelChardan** [comment]
Already done for behat :D

**Comment by anaelChardan** [comment]
Done

**Review by damien-carcel — APPROVED** [review]

**Comment by damien-carcel** [comment]
Perfect, thank you for this! 👍

**Comment by anaelChardan** [comment]
Welcome ! :)

**Pull request merged**
